# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def create_card_set_seed_data(apps, schema_editor):
    CardSet = apps.get_model("cards", "CardSet")
    
    CardSet.objects.using(schema_editor.connection.alias).bulk_create([
        CardSet(name="Core")        
    ])

def delete_card_set_seed_data(apps, schema_editor):
    CardSet = apps.get_model("cards", "CardSet")
    db_alias = schema_editor.connection.alias
    
    CardSet.objects.using(db_alias).filter(name="Core").delete()

def create_hero_team_seed_data(apps, schema_editor):
    HeroicTeam = apps.get_model("cards", "HeroicTeam")
    
    HeroicTeam.objects.using(schema_editor.connection.alias).bulk_create([
        HeroicTeam(team_name="X-Men", description="Born as mutants, with strange superpowers that set them apart, the X-Men are sworn to protect a world that hates and fears them."),
        HeroicTeam(team_name="Avengers", description="And there came a day unlike any other, when Earth's mightiest heroes and heroines found themselves united against a common threat. On that day, the Avengers were born."),
        HeroicTeam(team_name="S.H.I.E.L.D.", description="The 'Strategic Hazard Intervention Espionage Logistics Directorate' is a clandestine military and espionage organization led by Director Nick Fury."),
        HeroicTeam(team_name="Spider Friends", description="Spider-Man received his powers after being bit by a radioactive spider and along with his allies will protect New York from those who would threaten the innocent.")
    ])

def delete_hero_team_seed_data(apps, schema_editor):
    HeroicTeam = apps.get_model("cards", "HeroicTeam")
    db_alias = schema_editor.connection.alias
    
    HeroicTeam.objects.using(db_alias).filter(team_name="X-Men").delete()
    HeroicTeam.objects.using(db_alias).filter(team_name="Avengers").delete()
    HeroicTeam.objects.using(db_alias).filter(team_name="S.H.I.E.L.D.").delete()
    HeroicTeam.objects.using(db_alias).filter(team_name="Spider Friends").delete()

def create_hero_class_seed_data(apps, schema_editor):
    HeroClass = apps.get_model("cards", "HeroClass")
    
    HeroClass.objects.using(schema_editor.connection.alias).bulk_create([
        HeroClass(class_name="Strength", description="Strength heroes include heroes with raw strength, but also heroes with strength of will, determination, and strong leadership."),
        HeroClass(class_name="Instinct", description="Instinct heroes use savagery and quick reflexes to dominate combats. Some Instinct heroes use superhuman senses to get an edge on their opponents."),
        HeroClass(class_name="Covert", description="Covert heroes include heroes using trickery and deception to outwit their foes. They also include heroes making clever battle plans and heroes using subtle superpowers to gain subtle advantages."),
        HeroClass(class_name="Tech", description="Tech heroes include heroes using advanced weaponry, incredible gadgets, brilliant inventions, or next-generation science."),
        HeroClass(class_name="Ranged", description="Ranged heroes like to blow things up. Some Ranged heroes use inherent superpowers to blast things, while others use energy beams, elemental powers, and mental assaults."),
        HeroClass(class_name="Basic", description="Basic heroes include all the starting S.H.I.E.L.D. heroes and officers. They are heroes in their own way, but they don't quite get the job done as well as high-flying super heroes.")
    ])

def delete_hero_class_seed_data(apps, schema_editor):
    HeroClass = apps.get_model("cards", "HeroClass")
    db_alias = schema_editor.connection.alias
    
    HeroClass.objects.using(db_alias).filter(class_name="Strength").delete()
    HeroClass.objects.using(db_alias).filter(class_name="Instinct").delete()
    HeroClass.objects.using(db_alias).filter(class_name="Covert").delete()
    HeroClass.objects.using(db_alias).filter(class_name="Tech").delete()
    HeroClass.objects.using(db_alias).filter(class_name="Ranged").delete()
    HeroClass.objects.using(db_alias).filter(class_name="Basic").delete()

def create_hero_seed_data(apps, schema_editor):
    Hero = apps.get_model("cards", "Hero")
    CardSet = apps.get_model("cards", "CardSet")
    HeroicTeam = apps.get_model("cards", "HeroicTeam")
    db_alias = schema_editor.connection.alias
    
    core_set = CardSet.objects.using(db_alias).get(name="Core")

    xmen = HeroicTeam.objects.using(db_alias).get(team_name="X-Men")
    avengers = HeroicTeam.objects.using(db_alias).get(team_name="Avengers")
    shield = HeroicTeam.objects.using(db_alias).get(team_name="S.H.I.E.L.D.")
    spider = HeroicTeam.objects.using(db_alias).get(team_name="Spider Friends")
    
    Hero.objects.using(db_alias).bulk_create([
        Hero(name="Black Widow", static_folder="widow", hero_team=avengers, card_set=core_set),
        Hero(name="Captain America", static_folder="captain", hero_team=avengers, card_set=core_set),
        Hero(name="Cyclops", static_folder="cyclops", hero_team=xmen, card_set=core_set),
        Hero(name="Deadpool", static_folder="deadpool", card_set=core_set),
        Hero(name="Emma Frost", static_folder="emma", hero_team=xmen, card_set=core_set),
        Hero(name="Nick Fury", static_folder="fury", hero_team=shield, card_set=core_set),
        Hero(name="Gambit", static_folder="gambit", hero_team=xmen, card_set=core_set),
        Hero(name="Hawkeye", static_folder="hawkeye", hero_team=avengers, card_set=core_set),
        Hero(name="Hulk", static_folder="hulk", hero_team=avengers, card_set=core_set),
        Hero(name="Iron Man", static_folder="ironman", hero_team=avengers, card_set=core_set),
        Hero(name="Rogue", static_folder="rogue", hero_team=xmen, card_set=core_set),
        Hero(name="Spider-Man", static_folder="spider", hero_team=spider, card_set=core_set),
        Hero(name="Storm", static_folder="storm", hero_team=xmen, card_set=core_set),
        Hero(name="Thor", static_folder="thor", hero_team=avengers, card_set=core_set),
        Hero(name="Wolverine", static_folder="wolverine", hero_team=xmen, card_set=core_set),
    ])

def delete_hero_seed_data(apps, schema_editor):
    Hero = apps.get_model("cards", "Hero")
    db_alias = schema_editor.connection.alias
    
    Hero.objects.using(db_alias).filter(name="Black Widow").delete()
    Hero.objects.using(db_alias).filter(name="Captain America").delete()
    Hero.objects.using(db_alias).filter(name="Cyclops").delete()
    Hero.objects.using(db_alias).filter(name="Deadpool").delete()
    Hero.objects.using(db_alias).filter(name="Emma Frost").delete()
    Hero.objects.using(db_alias).filter(name="Nick Fury").delete()
    Hero.objects.using(db_alias).filter(name="Gambit").delete()
    Hero.objects.using(db_alias).filter(name="Hawkeye").delete()
    Hero.objects.using(db_alias).filter(name="Hulk").delete()
    Hero.objects.using(db_alias).filter(name="Iron Man").delete()
    Hero.objects.using(db_alias).filter(name="Rogue").delete()
    Hero.objects.using(db_alias).filter(name="Spider-Man").delete()
    Hero.objects.using(db_alias).filter(name="Storm").delete()
    Hero.objects.using(db_alias).filter(name="Thor").delete()
    Hero.objects.using(db_alias).filter(name="Wolverine").delete()

def create_hero_card_seed_data(apps, schema_editor):
    HeroCard = apps.get_model("cards", "HeroCard")
    Hero = apps.get_model("cards", "Hero")
    HeroClass = apps.get_model("cards", "HeroClass")
    db_alias = schema_editor.connection.alias

    widow = Hero.objects.using(db_alias).get(name="Black Widow")
    captain = Hero.objects.using(db_alias).get(name="Captain America")
    cyclops = Hero.objects.using(db_alias).get(name="Cyclops")
    deadpool = Hero.objects.using(db_alias).get(name="Deadpool")
    frost = Hero.objects.using(db_alias).get(name="Emma Frost")
    fury = Hero.objects.using(db_alias).get(name="Nick Fury")
    gambit = Hero.objects.using(db_alias).get(name="Gambit")
    hawkeye = Hero.objects.using(db_alias).get(name="Hawkeye")
    hulk = Hero.objects.using(db_alias).get(name="Hulk")
    iron = Hero.objects.using(db_alias).get(name="Iron Man")
    rogue = Hero.objects.using(db_alias).get(name="Rogue")
    spider = Hero.objects.using(db_alias).get(name="Spider-Man")
    storm = Hero.objects.using(db_alias).get(name="Storm")
    thor = Hero.objects.using(db_alias).get(name="Thor")
    wolverine = Hero.objects.using(db_alias).get(name="Wolverine")

    strength = HeroClass.objects.using(db_alias).get(class_name="Strength")
    instinct = HeroClass.objects.using(db_alias).get(class_name="Instinct")
    covert = HeroClass.objects.using(db_alias).get(class_name="Covert")
    tech = HeroClass.objects.using(db_alias).get(class_name="Tech")
    ranged = HeroClass.objects.using(db_alias).get(class_name="Ranged")

    HeroCard.objects.using(db_alias).bulk_create([
        #Black Widow
        HeroCard(major_text="Mission Accomplished", cost=2, base_recruit=0, base_attack=0, quantity=5, card_file_name="ma.jpg", hero=widow),
        HeroCard(major_text="Dangerous Rescue", cost=3, base_recruit=0, base_attack=2, quantity=5, card_file_name="dr.jpg", hero=widow),
        HeroCard(major_text="Covert Operation", cost=4, base_recruit=0, base_attack=0, quantity=3, card_file_name="co.jpg", hero=widow),
        HeroCard(major_text="Silent Sniper", cost=7, base_recruit=0, base_attack=4, quantity=1, card_file_name="ss.jpg", hero=widow),
        #Captain America
        HeroCard(major_text="Avengers Assemble!", cost=3, base_recruit=0, base_attack=0, quantity=5, card_file_name="aa.jpg", hero=captain),
        HeroCard(major_text="Perfect Teamwork", cost=4, base_recruit=0, base_attack=0, quantity=5, card_file_name="pt.jpg", hero=captain),
        HeroCard(major_text="Diving Block", cost=6, base_recruit=0, base_attack=4, quantity=3, card_file_name="db.jpg", hero=captain),
        HeroCard(major_text="A Day Unlike Any Other", cost=7, base_recruit=0, base_attack=3, quantity=1, card_file_name="aduao.jpg", hero=captain),
        #Cyclops
        HeroCard(major_text="Determination", cost=2, base_recruit=3, base_attack=0, quantity=5, card_file_name="d.jpg", hero=cyclops),
        HeroCard(major_text="Optic Blast", cost=3, base_recruit=0, base_attack=3, quantity=5, card_file_name="ob.jpg", hero=cyclops),
        HeroCard(major_text="Unending Energy", cost=6, base_recruit=0, base_attack=4, quantity=3, card_file_name="ue.jpg", hero=cyclops),
        HeroCard(major_text="X-Men United", cost=8, base_recruit=0, base_attack=6, quantity=1, card_file_name="xmu.jpg", hero=cyclops),
        #Deadpool
        HeroCard(major_text="Here, Hold This For A Second", cost=3, base_recruit=2, base_attack=0, quantity=5, card_file_name="hhtfas.jpg", hero=deadpool),
        HeroCard(major_text="Oddball", cost=5, base_recruit=0, base_attack=2, quantity=5, card_file_name="ob.jpg", hero=deadpool),
        HeroCard(major_text="Hey, Can I Get A Do-Over", cost=3, base_recruit=0, base_attack=2, quantity=3, card_file_name="hcigado.jpg", hero=deadpool),
        HeroCard(major_text="Random Acts of Unkindness", cost=7, base_recruit=0, base_attack=6, quantity=1, card_file_name="raou.jpg", hero=deadpool),
        #Emma Frost
        HeroCard(major_text="Mental Discipline", cost=3, base_recruit=1, base_attack=0, quantity=5, card_file_name="md.jpg", hero=frost),
        HeroCard(major_text="Shadowed Thoughts", cost=4, base_recruit=0, base_attack=2, quantity=5, card_file_name="st.jpg", hero=frost),
        HeroCard(major_text="Psychic Link", cost=5, base_recruit=0, base_attack=3, quantity=3, card_file_name="pl.jpg", hero=frost),
        HeroCard(major_text="Diamond Form", cost=7, base_recruit=0, base_attack=5, quantity=1, card_file_name="df.jpg", hero=frost),
        #Nick Fury
        HeroCard(major_text="High-Tech Weaponry", cost=3, base_recruit=0, base_attack=2, quantity=5, card_file_name="htw.jpg", hero=fury),
        HeroCard(major_text="Battlefield Promotion", cost=4, base_recruit=0, base_attack=0, quantity=5, card_file_name="bp.jpg", hero=fury),
        HeroCard(major_text="Legendary Commander", cost=6, base_recruit=0, base_attack=1, quantity=3, card_file_name="lc.jpg", hero=fury),
        HeroCard(major_text="Pure Fury", cost=8, base_recruit=0, base_attack=0, quantity=1, card_file_name="pf.jpg", hero=fury),
        #Gambit
        HeroCard(major_text="Stack The Deck", cost=2, base_recruit=0, base_attack=0, quantity=5, card_file_name="std.jpg", hero=gambit),
        HeroCard(major_text="Card Shark", cost=4, base_recruit=0, base_attack=2, quantity=5, card_file_name="cs.jpg", hero=gambit),
        HeroCard(major_text="Hypnotic Charm", cost=3, base_recruit=2, base_attack=0, quantity=3, card_file_name="hc.jpg", hero=gambit),
        HeroCard(major_text="High Stakes Jackpot", cost=7, base_recruit=0, base_attack=4, quantity=1, card_file_name="hsj.jpg", hero=gambit),
        #Hawkeye
        HeroCard(major_text="Quick Draw", cost=3, base_recruit=0, base_attack=1, quantity=5, card_file_name="qd.jpg", hero=hawkeye),
        HeroCard(major_text="Team Player", cost=4, base_recruit=0, base_attack=2, quantity=5, card_file_name="tp.jpg", hero=hawkeye),
        HeroCard(major_text="Covering Fire", cost=5, base_recruit=0, base_attack=3, quantity=3, card_file_name="cf.jpg", hero=hawkeye),
        HeroCard(major_text="Impossible Trick Shot", cost=7, base_recruit=0, base_attack=5, quantity=1, card_file_name="its.jpg", hero=hawkeye),
        #Hulk
        HeroCard(major_text="Growing Anger", cost=3, base_recruit=0, base_attack=2, quantity=5, card_file_name="ga.jpg", hero=hulk),
        HeroCard(major_text="Unstoppable Hulk", cost=4, base_recruit=0, base_attack=2, quantity=5, card_file_name="uh.jpg", hero=hulk),
        HeroCard(major_text="Crazed Rampage", cost=5, base_recruit=0, base_attack=4, quantity=3, card_file_name="cr.jpg", hero=hulk),
        HeroCard(major_text="Hulk Smash!", cost=7, base_recruit=0, base_attack=5, quantity=1, card_file_name="hs.jpg", hero=hulk),
        #Iron Man
        HeroCard(major_text="Repulsor Rays", cost=3, base_recruit=0, base_attack=2, quantity=5, card_file_name="rr.jpg", hero=iron),
        HeroCard(major_text="Endless Invention", cost=3, base_recruit=0, base_attack=0, quantity=5, card_file_name="ei.jpg", hero=iron),
        HeroCard(major_text="Arc Reactor", cost=5, base_recruit=0, base_attack=3, quantity=3, card_file_name="ar.jpg", hero=iron),
        HeroCard(major_text="Quantum Breakthrough", cost=7, base_recruit=0, base_attack=0, quantity=1, card_file_name="qb.jpg", hero=iron),
        #Rogue
        HeroCard(major_text="Energy Drain", cost=3, base_recruit=2, base_attack=0, quantity=5, card_file_name="ed.jpg", hero=rogue),
        HeroCard(major_text="Borrowed Brawn", cost=4, base_recruit=0, base_attack=1, quantity=5, card_file_name="bb.jpg", hero=rogue),
        HeroCard(major_text="Copy Powers", cost=5, base_recruit=0, base_attack=0, quantity=3, card_file_name="cp.jpg", hero=rogue),
        HeroCard(major_text="Steal Abilities", cost=8, base_recruit=0, base_attack=4, quantity=1, card_file_name="sa.jpg", hero=rogue),
        #Spider-Man
        HeroCard(major_text="Great Responsibility", cost=2, base_recruit=0, base_attack=1, quantity=5, card_file_name="gr.jpg", hero=spider),
        HeroCard(major_text="Astonishing Strength", cost=2, base_recruit=1, base_attack=0, quantity=5, card_file_name="as.jpg", hero=spider),
        HeroCard(major_text="Web-Shooters", cost=2, base_recruit=0, base_attack=0, quantity=3, card_file_name="ws.jpg", hero=spider),
        HeroCard(major_text="The Amazing Spider-Man", cost=2, base_recruit=0, base_attack=0, quantity=1, card_file_name="tasm.jpg", hero=spider),
        #Storm
        HeroCard(major_text="Lightning Bolt", cost=4, base_recruit=0, base_attack=2, quantity=5, card_file_name="lb.jpg", hero=storm),
        HeroCard(major_text="Gathering Stormclouds", cost=3, base_recruit=2, base_attack=0, quantity=5, card_file_name="gs.jpg", hero=storm),
        HeroCard(major_text="Spinning Cyclone", cost=4, base_recruit=0, base_attack=4, quantity=3, card_file_name="sc.jpg", hero=storm),
        HeroCard(major_text="Tidal Wave", cost=7, base_recruit=0, base_attack=5, quantity=1, card_file_name="tw.jpg", hero=storm),
        #Thor
        HeroCard(major_text="Odinson", cost=3, base_recruit=2, base_attack=0, quantity=5, card_file_name="o.jpg", hero=thor),
        HeroCard(major_text="Surge Of Power", cost=4, base_recruit=2, base_attack=0, quantity=5, card_file_name="sop.jpg", hero=thor),
        HeroCard(major_text="Call Lightning", cost=6, base_recruit=0, base_attack=3, quantity=3, card_file_name="cl.jpg", hero=thor),
        HeroCard(major_text="God Of Thunder", cost=8, base_recruit=5, base_attack=0, quantity=1, card_file_name="got.jpg", hero=thor),
        #Wolverine
        HeroCard(major_text="Keen Senses", cost=2, base_recruit=0, base_attack=1, quantity=5, card_file_name="ks.jpg", hero=wolverine),
        HeroCard(major_text="Healing Factor", cost=3, base_recruit=0, base_attack=2, quantity=5, card_file_name="hf.jpg", hero=wolverine),
        HeroCard(major_text="Frenzied Slashing", cost=5, base_recruit=0, base_attack=2, quantity=3, card_file_name="fs.jpg", hero=wolverine),
        HeroCard(major_text="Berserker Rage", cost=8, base_recruit=0, base_attack=0, quantity=1, card_file_name="br.jpg", hero=wolverine)
    ])

    #Black Widow
    HeroCard.objects.using(db_alias).get(major_text="Mission Accomplished").hero_class.add(tech);
    HeroCard.objects.using(db_alias).get(major_text="Dangerous Rescue").hero_class.add(covert);
    HeroCard.objects.using(db_alias).get(major_text="Covert Operation").hero_class.add(covert);
    HeroCard.objects.using(db_alias).get(major_text="Silent Sniper").hero_class.add(covert);
    #Captain America
    HeroCard.objects.using(db_alias).get(major_text="Avengers Assemble!").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="Perfect Teamwork").hero_class.add(strength);
    HeroCard.objects.using(db_alias).get(major_text="Diving Block").hero_class.add(tech);
    HeroCard.objects.using(db_alias).get(major_text="A Day Unlike Any Other").hero_class.add(covert);
    #Cyclops
    HeroCard.objects.using(db_alias).get(major_text="Determination").hero_class.add(strength);
    HeroCard.objects.using(db_alias).get(major_text="Optic Blast").hero_class.add(ranged);
    HeroCard.objects.using(db_alias).get(major_text="Unending Energy").hero_class.add(ranged);
    HeroCard.objects.using(db_alias).get(major_text="X-Men United").hero_class.add(ranged);
    #Deadpool
    HeroCard.objects.using(db_alias).get(major_text="Here, Hold This For A Second").hero_class.add(tech);
    HeroCard.objects.using(db_alias).get(major_text="Oddball").hero_class.add(covert);
    HeroCard.objects.using(db_alias).get(major_text="Hey, Can I Get A Do-Over").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="Random Acts of Unkindness").hero_class.add(instinct);
    #Emma Frost
    HeroCard.objects.using(db_alias).get(major_text="Mental Discipline").hero_class.add(ranged);
    HeroCard.objects.using(db_alias).get(major_text="Shadowed Thoughts").hero_class.add(covert);
    HeroCard.objects.using(db_alias).get(major_text="Psychic Link").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="Diamond Form").hero_class.add(strength);
    #Nick Fury
    HeroCard.objects.using(db_alias).get(major_text="High-Tech Weaponry").hero_class.add(tech);
    HeroCard.objects.using(db_alias).get(major_text="Battlefield Promotion").hero_class.add(covert);
    HeroCard.objects.using(db_alias).get(major_text="Legendary Commander").hero_class.add(strength);
    HeroCard.objects.using(db_alias).get(major_text="Pure Fury").hero_class.add(tech);
    #Gambit
    HeroCard.objects.using(db_alias).get(major_text="Stack The Deck").hero_class.add(covert);
    HeroCard.objects.using(db_alias).get(major_text="Card Shark").hero_class.add(ranged);
    HeroCard.objects.using(db_alias).get(major_text="Hypnotic Charm").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="High Stakes Jackpot").hero_class.add(instinct);
    #Hawkeye
    HeroCard.objects.using(db_alias).get(major_text="Quick Draw").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="Team Player").hero_class.add(tech);
    HeroCard.objects.using(db_alias).get(major_text="Covering Fire").hero_class.add(tech);
    HeroCard.objects.using(db_alias).get(major_text="Impossible Trick Shot").hero_class.add(tech);
    #Hulk
    HeroCard.objects.using(db_alias).get(major_text="Growing Anger").hero_class.add(strength);
    HeroCard.objects.using(db_alias).get(major_text="Unstoppable Hulk").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="Crazed Rampage").hero_class.add(strength);
    HeroCard.objects.using(db_alias).get(major_text="Hulk Smash!").hero_class.add(strength);
    #Iron Man
    HeroCard.objects.using(db_alias).get(major_text="Repulsor Rays").hero_class.add(ranged);
    HeroCard.objects.using(db_alias).get(major_text="Endless Invention").hero_class.add(tech);
    HeroCard.objects.using(db_alias).get(major_text="Arc Reactor").hero_class.add(tech);
    HeroCard.objects.using(db_alias).get(major_text="Quantum Breakthrough").hero_class.add(tech);
    #Rogue
    HeroCard.objects.using(db_alias).get(major_text="Energy Drain").hero_class.add(covert);
    HeroCard.objects.using(db_alias).get(major_text="Borrowed Brawn").hero_class.add(strength);
    HeroCard.objects.using(db_alias).get(major_text="Copy Powers").hero_class.add(covert);
    HeroCard.objects.using(db_alias).get(major_text="Steal Abilities").hero_class.add(strength);
    #Spider-Man
    HeroCard.objects.using(db_alias).get(major_text="Great Responsibility").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="Astonishing Strength").hero_class.add(strength);
    HeroCard.objects.using(db_alias).get(major_text="Web-Shooters").hero_class.add(tech);
    HeroCard.objects.using(db_alias).get(major_text="The Amazing Spider-Man").hero_class.add(covert);
    #Storm
    HeroCard.objects.using(db_alias).get(major_text="Lightning Bolt").hero_class.add(ranged);
    HeroCard.objects.using(db_alias).get(major_text="Gathering Stormclouds").hero_class.add(ranged);
    HeroCard.objects.using(db_alias).get(major_text="Spinning Cyclone").hero_class.add(covert);
    HeroCard.objects.using(db_alias).get(major_text="Tidal Wave").hero_class.add(ranged);
    #Thor
    HeroCard.objects.using(db_alias).get(major_text="Odinson").hero_class.add(strength);
    HeroCard.objects.using(db_alias).get(major_text="Surge Of Power").hero_class.add(ranged);
    HeroCard.objects.using(db_alias).get(major_text="Call Lightning").hero_class.add(ranged);
    HeroCard.objects.using(db_alias).get(major_text="God Of Thunder").hero_class.add(ranged);
    #Wolverine
    HeroCard.objects.using(db_alias).get(major_text="Keen Senses").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="Healing Factor").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="Frenzied Slashing").hero_class.add(instinct);
    HeroCard.objects.using(db_alias).get(major_text="Berserker Rage").hero_class.add(instinct);

def delete_hero_card_seed_data(apps, schema_editor):
    HeroCard = apps.get_model("cards", "HeroCard")
    db_alias = schema_editor.connection.alias

    #Black Widow
    HeroCard.objects.using(db_alias).filter(major_text="Mission Accomplished").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Dangerous Rescue").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Covert Operation").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Silent Sniper").delete()
    #Captain America
    HeroCard.objects.using(db_alias).filter(major_text="Avengers Assemble!").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Perfect Teamwork").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Diving Block").delete()
    HeroCard.objects.using(db_alias).filter(major_text="A Day Unlike Any Other").delete()
    #Cyclops
    HeroCard.objects.using(db_alias).filter(major_text="Determination").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Optic Blast").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Unending Energy").delete()
    HeroCard.objects.using(db_alias).filter(major_text="X-Men United").delete()
    #Deadpool
    HeroCard.objects.using(db_alias).filter(major_text="Here, Hold This For A Second").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Oddball").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Hey, Can I Get A Do-Over").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Random Acts of Unkindness").delete()
    #Emma Frost
    HeroCard.objects.using(db_alias).filter(major_text="Mental Discipline").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Shadowed Thoughts").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Psychic Link").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Diamond Form").delete()
    #Nick Fury
    HeroCard.objects.using(db_alias).filter(major_text="High-Tech Weaponry").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Battlefield Promotion").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Legendary Commander").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Pure Fury").delete()
    #Gambit
    HeroCard.objects.using(db_alias).filter(major_text="Stack The Deck").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Card Shark").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Hypnotic Charm").delete()
    HeroCard.objects.using(db_alias).filter(major_text="High Stakes Jackpot").delete()
    #Hawkeye
    HeroCard.objects.using(db_alias).filter(major_text="Quick Draw").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Team Player").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Covering Fire").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Impossible Trick Shot").delete()
    #Hulk
    HeroCard.objects.using(db_alias).filter(major_text="Growing Anger").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Unstoppable Hulk").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Crazed Rampage").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Hulk Smash!").delete()
    #Iron Man
    HeroCard.objects.using(db_alias).filter(major_text="Repulsor Rays").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Endless Invention").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Arc Reactor").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Quantum Breakthrough").delete()
    #Rogue
    HeroCard.objects.using(db_alias).filter(major_text="Energy Drain").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Borrowed Brawn").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Copy Powers").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Steal Abilities").delete()
    #Storm
    HeroCard.objects.using(db_alias).filter(major_text="Lightning Bolt").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Gathering Stormclouds").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Spinning Cyclone").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Tidal Wave").delete()
    #Thor
    HeroCard.objects.using(db_alias).filter(major_text="Odinson").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Surge Of Power").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Call Lightning").delete()
    HeroCard.objects.using(db_alias).filter(major_text="God Of Thunder").delete()
    #Wolverine
    HeroCard.objects.using(db_alias).filter(major_text="Keen Senses").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Healing Factor").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Frenzied Slashing").delete()
    HeroCard.objects.using(db_alias).filter(major_text="Berserker Rage").delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('static_folder', models.CharField(max_length=20)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardSet')),
            ],
        ),
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_text', models.CharField(max_length=50)),
                ('cost', models.PositiveSmallIntegerField()),
                ('base_recruit', models.PositiveSmallIntegerField()),
                ('base_attack', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('card_file_name', models.CharField(max_length=20)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='HeroClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_column='Name', max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HeroicTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_column='Name', max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='herocard',
            name='hero_class',
            field=models.ManyToManyField(db_table='cards_herocard_heroclass', to='cards.HeroClass'),
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.HeroicTeam'),
        ),
        migrations.RunPython(create_card_set_seed_data, delete_card_set_seed_data),
        migrations.RunPython(create_hero_team_seed_data, delete_hero_team_seed_data),
        migrations.RunPython(create_hero_class_seed_data, delete_hero_class_seed_data),
        migrations.RunPython(create_hero_seed_data, delete_hero_seed_data),
        migrations.RunPython(create_hero_card_seed_data, delete_hero_card_seed_data)
    ]
